### ISSUE TITLE
[BUG]: Updating via cli from dev version is broken

### ISSUE THREAD

**Issue by w4bremer** [apigear-io/cli#80]
### Description of the bug

Updating from an installed cli dev version does not suggest updating to the latest release.
Probably there is a bug in the algorithm identifying the latest release?

### Steps To Reproduce

1. have a dev version installed
2. try to update it via the cli update command
$ apigear update
23:11:59 INF check for updates: apigear-io/cli
New release 0.9.0 available.
See https://github.com/apigear-io/cli/releases/tag/v0.9.0.
do you want to update? [y/N]: No

**Comment by jryannel** [comment]
Not sure, for me cli delivers v0.28.3 which is the latest version.

See 
```
➜  cli git:(jr-readonly-properties) ./bin/apigear update
15:43:43 INF check for updates: apigear-io/cli
New release 0.28.3 available.
See https://github.com/apigear-io/cli/releases/tag/v0.28.3.
do you want to update? [y/N]: Yes
updating to 0.28.3
```

Can you re-check?

**Comment by jryannel** [comment]
Seems to be working
